env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - task update-version-file

dist: build

archives:
  - format_overrides:
      - goos: windows
        format: zip

builds:
  - main: './main.go'
    binary: 'git-ninja'
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    targets:
      - linux_amd64
      - darwin_arm64
      - darwin_amd64

brews:
  -
    name: 'git-ninja'
    homepage: 'https://github.com/permafrost-dev/git-ninja'
    description: 'Git alias commands'
    license: "MIT"
    tap:
      owner: 'permafrost-dev'
      name: homebrew-git-ninja
      branch: main

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
